import type {
  ExerciseMotionMedia,
  ExerciseMediaTileIndex,
  ExerciseRecord,
  ExerciseStillImageMedia,
  KneeForwardSeedData,
  RehabPhase,
  RehabRoutine,
  SourceMetadata,
} from "./types";

export const SAFETY_NOTICE =
  "Use only exercises and loading approved for this episode by your surgeon or rehabilitation clinician. Progress by agreed clinical criteria, not by the calendar alone. Stop and contact your care team for new or worsening pain, swelling, instability, loss of motion, wound concerns, calf pain, chest pain, or shortness of breath.";

export const sourceMetadata = [
  {
    id: "source-care-team",
    kind: "care_team_plan",
    title: "Individual care-team rehabilitation plan",
    publisher: "Treating surgeon and rehabilitation clinician",
    note: "The individual plan takes priority over bundled educational content and supplies all exercise dosage and restrictions.",
  },
  {
    id: "source-aaos-acl",
    kind: "clinical_guideline",
    title: "Management of Anterior Cruciate Ligament Injuries Clinical Practice Guideline",
    publisher: "American Academy of Orthopaedic Surgeons",
    url: "https://www.aaos.org/globalassets/quality-and-practice-resources/anterior-cruciate-ligament-injuries/aclcpg.pdf",
    publishedYear: 2022,
    accessedOn: "2026-08-12",
    note: "General ACL injury guidance. Individual treatment and rehabilitation decisions remain clinician-directed.",
  },
  {
    id: "source-aspetar-aclr-cpg",
    kind: "clinical_guideline",
    title: "Aspetar clinical practice guideline on rehabilitation after anterior cruciate ligament reconstruction",
    publisher: "British Journal of Sports Medicine",
    url: "https://bjsm.bmj.com/content/57/9/500",
    publishedYear: 2023,
    accessedOn: "2026-08-12",
    note: "Supports criteria-based rehabilitation; it does not replace clinician assessment or procedure-specific restrictions.",
  },
  {
    id: "source-mgh-aclr",
    kind: "rehab_protocol",
    title: "Rehabilitation Protocol for Anterior Cruciate Ligament Reconstruction",
    publisher: "Massachusetts General Brigham Sports Medicine",
    url: "https://www.massgeneral.org/assets/MGH/pdf/orthopaedics/sports-medicine/physical-therapy/rehabilitation-protocol-for-ACL.pdf",
    note: "General reference only. Graft choice, associated procedures, symptoms, and clinician direction may change appropriate progression.",
  },
  {
    id: "source-mgh-nonoperative-acl",
    kind: "rehab_protocol",
    title: "Rehabilitation Protocol for Non-Operative Management of ACL Injuries",
    publisher: "Massachusetts General Brigham Sports Medicine",
    url: "https://www.massgeneral.org/assets/MGH/pdf/orthopaedics/sports-medicine/physical-therapy/rehabilitation-protocol-for-non-operative-ACL-repair.pdf",
    accessedOn: "2026-08-12",
    note: "General education only. The treating clinician sets weight-bearing, motion, exercise, and progression for the individual knee.",
  },
  {
    id: "source-osu-aclr",
    kind: "rehab_protocol",
    title: "ACL Reconstruction Clinical Practice Guideline",
    publisher: "The Ohio State University Wexner Medical Center",
    url: "https://wexnermedical.osu.edu/-/media/files/wexnermedical/patient-care/healthcare-services/sports-medicine/education/medical-professionals/knee-ankle-and-foot/acl_reconstruction.pdf",
    accessedOn: "2026-08-12",
    note: "Criteria-based reference. Graft choice and associated meniscus, cartilage, or ligament procedures override generic exercise suggestions.",
  },
  {
    id: "source-royal-devon-aclr",
    kind: "rehab_protocol",
    title: "Preparing for Your Anterior Cruciate Ligament Reconstruction",
    publisher: "Royal Devon University Healthcare NHS Foundation Trust",
    url: "https://www.royaldevon.nhs.uk/media/dcejpp2l/preparing-for-your-anterior-cruciate-ligament-reconstruction-at-swaoc-rd-e-24-035-002a.pdf",
    publishedYear: 2026,
    accessedOn: "2026-08-12",
    note: "Patient guidance used to support post-operative warning-sign education; local clinical instructions take priority.",
  },
] as const satisfies readonly SourceMetadata[];

export const rehabPhases = [
  {
    id: "prehab",
    order: 1,
    name: "Pre-surgery preparation",
    shortName: "Prepare",
    tone: "prepare",
    summary: "Build a calm, mobile knee and maintain whole-leg capacity before surgery.",
    goals: ["Manage symptoms", "Restore clinician-agreed motion", "Maintain quadriceps and hip capacity"],
    entryCriteria: ["Surgery is being considered or scheduled", "The care team has cleared pre-operative exercise"],
    exitCriteria: ["Clinician-agreed symptom and motion goals are met", "The surgical plan and immediate post-operative plan are understood"],
    safetyNote: SAFETY_NOTICE,
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
  },
  {
    id: "protect-and-settle",
    order: 2,
    name: "Protect and settle",
    shortName: "Protect",
    tone: "protect",
    summary: "Follow surgical restrictions while addressing swelling, motion, and muscle activation.",
    goals: ["Protect healing tissue", "Manage swelling", "Recover clinician-agreed extension and flexion", "Restore quadriceps activation"],
    entryCriteria: ["Surgery is complete", "The post-operative plan and weight-bearing restrictions are documented"],
    exitCriteria: ["Wound and swelling are acceptable to the care team", "Motion, quadriceps control, and walking meet clinician-set criteria"],
    safetyNote: SAFETY_NOTICE,
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-mgh-aclr"],
  },
  {
    id: "rebuild-capacity",
    order: 3,
    name: "Rebuild capacity",
    shortName: "Rebuild",
    tone: "rebuild",
    summary: "Develop movement quality, strength, and everyday function within symptom limits.",
    goals: ["Normalize daily movement", "Build knee and hip strength", "Improve single-leg control"],
    entryCriteria: ["The clinician has cleared progressive strengthening", "The knee tolerates the current plan without an unacceptable reaction"],
    exitCriteria: ["Strength and functional tests meet clinician-set thresholds", "Training does not cause an unacceptable pain or swelling response"],
    safetyNote: SAFETY_NOTICE,
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
  },
  {
    id: "advance-performance",
    order: 4,
    name: "Advance performance",
    shortName: "Advance",
    tone: "advance",
    summary: "Build higher-level strength, power, balance, and task-specific control.",
    goals: ["Reduce side-to-side deficits", "Build task-specific capacity", "Prepare for return-to-activity testing"],
    entryCriteria: ["The care team has cleared higher-load and impact preparation", "Foundational strength and movement criteria are met"],
    exitCriteria: ["Objective strength, hop, movement, and symptom criteria set by the care team are met", "Psychological readiness has been reviewed"],
    safetyNote: SAFETY_NOTICE,
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
  },
  {
    id: "return-and-maintain",
    order: 5,
    name: "Return and maintain",
    shortName: "Return",
    tone: "return",
    summary: "Reintroduce chosen activities gradually and maintain long-term knee capacity.",
    goals: ["Return through a graded exposure plan", "Maintain strength and movement quality", "Monitor workload and knee response"],
    entryCriteria: ["The surgeon and rehabilitation clinician have cleared the planned activity", "Activity-specific test criteria are met"],
    exitCriteria: ["The person and care team agree that the episode goals are met", "A maintenance and flare-response plan is in place"],
    safetyNote: SAFETY_NOTICE,
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
  },
] as const satisfies readonly RehabPhase[];

const media = (
  _sheet: "foundations" | "strength",
  tileIndex: ExerciseMediaTileIndex,
  alt: string,
  visualScope: "exact_variation" | "generic_pattern" = "exact_variation",
) => ({
  kind: "sprite" as const,
  spriteSheetId: `exercise-reference-${_sheet}` as const,
  src: `/assets/exercise-panels/${_sheet}-${tileIndex}.webp`,
  tileIndex,
  panelCount: 8 as const,
  alt,
  visualScope,
  clinicalReviewStatus: "pending" as const,
});

const generatedStill = (slug: string, alt: string): ExerciseStillImageMedia => ({
  kind: "image",
  src: `/assets/exercise-stills/${slug}.webp`,
  alt,
  width: 1024,
  height: 1024,
  sourcePageUrl: "https://openai.com/index/introducing-4o-image-generation/",
  creator: "OpenAI image generation",
  permissionText: "Created for this project.",
  attributionText: "Original image generated for Knee Forward.",
  visualScope: "exact_variation",
  clinicalReviewStatus: "pending",
});

const gymVisualMotionSources = {
  "0020-xAySMB0": { sourceTitle: "Balance board", visualScope: "generic_pattern" },
  "0381-SSsBDwB": { sourceTitle: "Dumbbell rear lunge", visualScope: "generic_pattern" },
  "0411-H6ybluc": { sourceTitle: "Dumbbell single leg squat", visualScope: "generic_pattern" },
  "0585-my33uHU": { sourceTitle: "Lever leg extension", visualScope: "generic_pattern" },
  "0597-CHpahtl": { sourceTitle: "Lever seated hip abduction", visualScope: "generic_pattern" },
  "0628-O95afRA": { sourceTitle: "Monster walk", visualScope: "exact_variation" },
  "0710-7WaDzyL": { sourceTitle: "Side hip abduction", visualScope: "generic_pattern" },
  "0730-LNE3wfo": { sourceTitle: "Single leg platform slide", visualScope: "generic_pattern" },
  "0795-C5jncD2": { sourceTitle: "Standing single leg curl", visualScope: "generic_pattern" },
  "1002-bbLR7fB": { sourceTitle: "Band lying straight leg raise", visualScope: "generic_pattern" },
  "1008-d5bTEPV": { sourceTitle: "Band step-up", visualScope: "generic_pattern" },
  "1368-uL9CsKm": { sourceTitle: "Ankle circles", visualScope: "generic_pattern" },
  "1373-bJYHBIN": { sourceTitle: "Bodyweight standing calf raise", visualScope: "exact_variation" },
  "1377-m0tCHqc": { sourceTitle: "Calf stretch with hands against wall", visualScope: "exact_variation" },
  "1387-0jp9Rlz": { sourceTitle: "One leg floor calf raise", visualScope: "exact_variation" },
  "1459-rR0LJzx": { sourceTitle: "Dumbbell Romanian deadlift", visualScope: "generic_pattern" },
  "1425-WWD6FzI": { sourceTitle: "Sled 45 degrees one leg press", visualScope: "exact_variation" },
  "2138-H1PESYI": { sourceTitle: "Stationary bike run v. 3", visualScope: "exact_variation" },
  "2805-daBmy1Y": { sourceTitle: "Dumbbell single leg deadlift with stepbox support", visualScope: "generic_pattern" },
  "3007-Y1MsI1l": { sourceTitle: "Resistance band leg extension", visualScope: "generic_pattern" },
  "3013-u0cNiij": { sourceTitle: "Low glute bridge on floor", visualScope: "exact_variation" },
  "3119-75Bgtjy": { sourceTitle: "Potty squat", visualScope: "exact_variation" },
  "3132-b63ZzGe": { sourceTitle: "Potty squat with support", visualScope: "exact_variation" },
  "3195-UXpKJoq": { sourceTitle: "Lever lying two-one leg curl", visualScope: "generic_pattern" },
  "3470-kMzUs9Y": { sourceTitle: "Forward lunge", visualScope: "generic_pattern" },
  "3543-wfotm7S": { sourceTitle: "Bodyweight drop jump squat", visualScope: "generic_pattern" },
  "3561-GibBPPg": { sourceTitle: "Glute bridge march", visualScope: "exact_variation" },
} as const;

const gymVisualMotion = (
  assetId: keyof typeof gymVisualMotionSources,
  alt: string,
  visualScope?: "exact_variation" | "generic_pattern",
): ExerciseMotionMedia => {
  const source = gymVisualMotionSources[assetId];
  return {
    kind: "motion",
    sources: [
      { src: `/assets/motion/gymvisual/${assetId}.webm`, mimeType: "video/webm" },
      { src: `/assets/motion/gymvisual/${assetId}.mp4`, mimeType: "video/mp4" },
    ],
    posterSrc: `/assets/motion/gymvisual/${assetId}.jpg`,
    alt,
    sourcePageUrl: `https://github.com/hasaneyldrm/exercises-dataset/blob/7455efae41b330c265e7cd4b78dfa848e7ce5ebd/videos/${assetId}.gif`,
    creator: "Gym visual",
    permissionText: "Project owner confirmed approval for this use",
    licenseUrl: "https://gymvisual.com/content/3-terms-and-conditions-of-use",
    attributionText: `© Gym visual - https://gymvisual.com/. ${source.sourceTitle}, provided through hasaneyldrm/exercises-dataset. The project owner confirmed approval for this use and its exercise mapping.`,
    visualScope: visualScope ?? source.visualScope,
    clinicalReviewStatus: "reviewed",
    width: 180,
    height: 180,
    changesMade: "Source GIF converted to WebM and MP4; no GIF is used at runtime.",
  };
};

const standardStopSignals = [
  "Stop if the knee gives way or the movement feels unsafe.",
  "Stop if pain or swelling exceeds the response agreed with your clinician.",
] as const;

export const exercises = [
  {
    id: "single-leg-knee-extension-machine",
    name: "Single-leg knee extension machine",
    shortName: "Knee extension",
    category: "strength",
    equipment: ["knee_extension_machine"],
    description: "Isolated knee-extension strength work using the range and load approved for the current episode.",
    cues: ["Align the machine pivot with the knee", "Move smoothly through the approved range", "Keep the hips settled"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
    demoMedia: gymVisualMotion("0585-my33uHU", "General machine reference showing a bilateral knee extension rather than the named single-leg variation"),
    media: media("strength", 0, "Single-leg knee extension machine exercise"),
  },
  {
    id: "single-leg-hamstring-curl-machine",
    name: "Single-leg hamstring curl machine",
    shortName: "Hamstring curl",
    category: "strength",
    equipment: ["hamstring_curl_machine"],
    description: "Single-leg hamstring strengthening with clinician-approved timing, range, and load.",
    cues: ["Keep the pelvis steady", "Curl without momentum", "Return with control"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("3195-UXpKJoq", "General machine reference showing a lying two-one leg curl rather than the named seated single-leg variation"),
    media: media("strength", 1, "Single-leg hamstring curl machine exercise"),
  },
  {
    id: "single-leg-press",
    name: "Single-leg press",
    shortName: "Leg press",
    category: "strength",
    equipment: ["leg_press_machine"],
    description: "Supported single-leg pushing strength through an individually approved range.",
    cues: ["Keep the foot planted", "Track the knee in line with the foot", "Control both directions"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
    demoMedia: gymVisualMotion("1425-WWD6FzI", "Looping demonstration of a 45-degree single-leg press"),
    media: media("strength", 2, "Single-leg press exercise"),
  },
  {
    id: "squat",
    name: "Squat",
    shortName: "Squat",
    category: "strength",
    equipment: ["none"],
    description: "A coordinated hip, knee, and ankle strength pattern adjusted to current symptoms and clearance.",
    cues: ["Use a comfortable stance", "Keep the knees tracking with the feet", "Share pressure across the whole foot"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg"],
    demoMedia: gymVisualMotion("3119-75Bgtjy", "Looping demonstration of a bodyweight squat pattern"),
    media: media("strength", 3, "Bodyweight squat exercise"),
  },
  {
    id: "supported-mini-squat",
    name: "Supported mini squat",
    shortName: "Mini squat",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A shallow supported squat for controlled hip, knee, and ankle loading. Your clinician sets the support, depth, and timing.",
    cues: ["Hold a stable chair or rail", "Keep both feet fully planted", "Track the knees with the feet and stay within the approved depth"],
    stopSignals: [...standardStopSignals, "Stop if either knee buckles, the support moves, or you cannot rise with control."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-aspetar-aclr-cpg"],
    demoMedia: gymVisualMotion("3132-b63ZzGe", "Looping demonstration of a shallow squat using stable hand support"),
    media: generatedStill("supported-mini-squat", "Supported shallow mini-squat exercise"),
  },
  {
    id: "standing-single-leg-heel-raise",
    name: "Standing single-leg heel raise",
    shortName: "Heel raise",
    category: "strength",
    equipment: ["support_surface"],
    description: "Single-leg calf strengthening with light hand support as needed for balance.",
    cues: ["Rise straight upward", "Keep pressure through the forefoot", "Lower slowly"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("1387-0jp9Rlz", "Looping demonstration of a single-leg floor calf raise"),
    media: media("strength", 4, "Standing single-leg heel raise with support"),
  },
  {
    id: "standing-hip-abduction-external-rotation-fire-hydrant",
    name: "Standing hip abduction with external rotation / fire hydrant",
    shortName: "Standing fire hydrant",
    category: "strength",
    equipment: ["support_surface", "resistance_band"],
    description: "Standing hip strength and pelvic-control exercise, performed with support or a clinician-approved band.",
    cues: ["Keep the trunk tall", "Keep the pelvis level", "Move from the hip without twisting the stance knee"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("0597-CHpahtl", "General hip-abduction reference; the seated machine setup differs from the standing fire-hydrant variation"),
    media: media("strength", 5, "Standing hip abduction with external rotation exercise"),
  },
  {
    id: "modified-single-leg-deadlift",
    name: "Modified single-leg deadlift",
    shortName: "Modified deadlift",
    category: "strength",
    equipment: ["support_surface"],
    description: "A supported single-leg hip hinge used to develop posterior-chain strength and control.",
    cues: ["Use hand support as needed", "Reach the hips back", "Keep the stance knee softly bent and aligned"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("2805-daBmy1Y", "General supported single-leg hip-hinge reference using a dumbbell and stepbox"),
    media: media("strength", 6, "Supported modified single-leg deadlift exercise"),
  },
  {
    id: "stationary-bike",
    name: "Stationary bike",
    shortName: "Bike",
    category: "conditioning",
    equipment: ["stationary_bike"],
    description: "Low-impact cycling for clinician-approved motion, warm-up, or conditioning.",
    cues: ["Set the seat for the approved knee range", "Pedal smoothly", "Use only approved resistance"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "protect-and-settle", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("2138-H1PESYI", "Looping demonstration of a stationary-bike movement pattern"),
    media: media("strength", 7, "Stationary bike exercise"),
  },
  {
    id: "standing-wall-calf-stretch",
    name: "Standing wall calf stretch",
    shortName: "Wall calf stretch",
    category: "range_of_motion",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A supported calf-mobility exercise performed only within the stretch position and symptom response selected by your clinician.",
    cues: ["Place both hands on a stable wall", "Point both feet forward and keep the rear heel down", "Use a gentle stretch without bouncing"],
    stopSignals: [...standardStopSignals, "Stop and contact your care team for new calf pain with swelling, warmth, or redness."],
    eligiblePhaseIds: ["prehab", "protect-and-settle", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("1377-m0tCHqc", "Looping demonstration of a standing calf stretch against a wall"),
    media: generatedStill("standing-wall-calf-stretch", "Standing calf stretch with both hands against a wall"),
  },
  {
    id: "heel-slide",
    name: "Heel slide",
    shortName: "Heel slide",
    category: "range_of_motion",
    equipment: ["none"],
    description: "Supported knee bending and straightening within the range approved by the care team.",
    cues: ["Slide slowly", "Keep the heel supported", "Stay within the agreed symptom response"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "protect-and-settle"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("0730-LNE3wfo", "General sliding-leg reference; the standing platform setup differs from a supported supine heel slide"),
    media: media("foundations", 0, "Heel slide range-of-motion exercise"),
  },
  {
    id: "quad-set",
    name: "Quad set",
    shortName: "Quad set",
    category: "activation",
    equipment: ["none"],
    description: "Isometric quadriceps activation with the leg supported.",
    cues: ["Tighten the front of the thigh", "Gently press the knee toward the support", "Keep breathing"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "protect-and-settle"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("0585-my33uHU", "General quadriceps knee-extension reference; this moving machine demonstration differs from an isometric quad set"),
    media: media("foundations", 1, "Quadriceps set exercise"),
  },
  {
    id: "ankle-pump",
    name: "Ankle pump",
    shortName: "Ankle pump",
    category: "range_of_motion",
    equipment: ["none"],
    description: "Gentle ankle motion used when approved in the immediate recovery plan.",
    cues: ["Move the ankle up and down", "Keep the leg relaxed", "Move comfortably"],
    stopSignals: ["Stop and seek urgent medical advice for calf pain, chest pain, or shortness of breath."],
    eligiblePhaseIds: ["protect-and-settle"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("1368-uL9CsKm", "General ankle-mobility reference showing ankle circles rather than an up-and-down ankle pump"),
    media: media("foundations", 2, "Ankle pump exercise"),
  },
  {
    id: "straight-leg-raise",
    name: "Straight-leg raise",
    shortName: "Leg raise",
    category: "activation",
    equipment: ["none"],
    description: "A straight-knee leg lift performed only when the quadriceps can hold the knee as directed.",
    cues: ["Set the quadriceps first", "Keep the knee straight", "Lift and lower with control"],
    stopSignals: [...standardStopSignals, "Stop if the knee cannot remain straight; ask your clinician to reassess."],
    eligiblePhaseIds: ["prehab", "protect-and-settle", "rebuild-capacity"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("1002-bbLR7fB", "General straight-leg raise reference using band resistance rather than the unloaded rehabilitation variation"),
    media: media("foundations", 3, "Straight-leg raise exercise"),
  },
  {
    id: "bridge",
    name: "Bridge",
    shortName: "Bridge",
    category: "strength",
    equipment: ["none"],
    description: "Hip-extension strength work with both feet supported.",
    cues: ["Brace gently", "Press through the feet", "Lift without arching the lower back"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "protect-and-settle", "rebuild-capacity"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("3013-u0cNiij", "Looping demonstration of a two-leg floor bridge"),
    media: media("foundations", 4, "Bridge exercise"),
  },
  {
    id: "bridge-march",
    name: "Bridge march",
    shortName: "Bridge march",
    category: "strength",
    planEligible: false,
    equipment: ["none"],
    description: "An alternating single-leg bridge progression used only after two-leg bridging and single-leg loading have been cleared.",
    cues: ["Build a steady two-leg bridge first", "Keep the pelvis level as one foot lifts a small distance", "Lower the foot softly before changing sides"],
    stopSignals: [...standardStopSignals, "Stop for hamstring graft-site pain, cramping that changes control, or a marked pelvic drop."],
    eligiblePhaseIds: ["rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-aspetar-aclr-cpg"],
    demoMedia: gymVisualMotion("3561-GibBPPg", "Looping demonstration of an alternating bridge march"),
    media: generatedStill("bridge-march", "Bridge-march exercise with one foot lifted"),
  },
  {
    id: "step-up",
    name: "Step-up",
    shortName: "Step-up",
    category: "strength",
    equipment: ["step", "support_surface"],
    description: "A functional single-leg loading task using an approved step height and support.",
    cues: ["Place the whole foot on the step", "Track the knee with the foot", "Rise and lower with control"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("1008-d5bTEPV", "General step-up reference using a resistance band rather than the supported unloaded variation"),
    media: media("foundations", 5, "Step-up exercise"),
  },
  {
    id: "single-leg-balance",
    name: "Single-leg balance",
    shortName: "Single-leg balance",
    category: "balance",
    equipment: ["support_surface"],
    description: "Supported balance practice on one leg under clinician-approved conditions.",
    cues: ["Stand near stable support", "Keep the pelvis level", "Maintain a soft, aligned knee"],
    stopSignals: [...standardStopSignals, "Stop if you cannot practice without a fall risk."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("0020-xAySMB0", "General single-leg balance reference using a balance board rather than a stable floor and nearby support"),
    media: media("foundations", 6, "Single-leg balance beside a stable support"),
  },
  {
    id: "lateral-band-walk",
    name: "Lateral band walk",
    shortName: "Band walk",
    category: "strength",
    equipment: ["resistance_band"],
    description: "Side-stepping hip-strength exercise using clinician-selected band placement and resistance.",
    cues: ["Keep steady band tension", "Take controlled side steps", "Keep feet and knees aligned"],
    stopSignals: standardStopSignals,
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team"],
    demoMedia: gymVisualMotion("0628-O95afRA", "Looping demonstration of controlled lateral steps with a resistance band"),
    media: media("foundations", 7, "Lateral resistance-band walk exercise"),
  },
  {
    id: "seated-knee-extension",
    name: "Seated knee extension",
    shortName: "Seated extension",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface", "ankle_weight"],
    description: "Open-chain quadriceps strengthening through only the range and resistance selected for this knee.",
    cues: ["Sit tall with the thigh supported", "Straighten only through the approved range", "Lift and lower without swinging"],
    stopSignals: [...standardStopSignals, "Stop for increasing pain at the front of the knee or a worsening swelling response."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-osu-aclr"],
    demoMedia: gymVisualMotion("0585-my33uHU", "General seated knee-extension machine reference; resistance and range differ from the ankle-weight variation"),
    media: generatedStill("seated-knee-extension", "Seated knee-extension exercise"),
  },
  {
    id: "supported-standing-knee-curl",
    name: "Supported standing knee curl",
    shortName: "Standing knee curl",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface", "ankle_weight"],
    description: "Standing hamstring strengthening with stable hand support and clinician-approved resistance.",
    cues: ["Hold a stable support", "Keep the thighs beside each other", "Bend and lower without swinging the pelvis"],
    stopSignals: [...standardStopSignals, "Stop for pain at a hamstring graft-donor site or a cramp that changes control."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-osu-aclr"],
    demoMedia: gymVisualMotion("0795-C5jncD2", "General standing single-leg knee-curl reference without the named stable hand support"),
    media: generatedStill("supported-standing-knee-curl", "Supported standing knee-curl exercise"),
  },
  {
    id: "supported-double-leg-calf-raise",
    name: "Supported double-leg calf raise",
    shortName: "Supported calf raise",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A two-leg calf raise using stable support, progressed only when weight-bearing and balance are cleared.",
    cues: ["Use a stable support", "Rise straight upward through both forefeet", "Lower slowly with equal control"],
    stopSignals: [...standardStopSignals, "Stop if you cannot keep your balance without pulling on the support."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("1373-bJYHBIN", "Looping demonstration of a supported bodyweight double-leg calf raise"),
    media: generatedStill("supported-double-leg-calf-raise", "Supported double-leg calf-raise exercise"),
  },
  {
    id: "supported-standing-hip-abduction",
    name: "Supported standing hip abduction",
    shortName: "Standing hip abduction",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "Standing hip-strength and pelvic-control work with stable support and clinician-selected range.",
    cues: ["Stand tall beside stable support", "Keep the toes facing forward", "Move the leg sideways without leaning or hiking the pelvis"],
    stopSignals: [...standardStopSignals, "Stop if the stance knee twists, buckles, or feels unstable."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-mgh-nonoperative-acl"],
    demoMedia: gymVisualMotion("0710-7WaDzyL", "General hip-abduction reference; body position and support differ from the named standing variation"),
    media: generatedStill("supported-standing-hip-abduction", "Supported standing hip-abduction exercise"),
  },
  {
    id: "supported-forward-lunge",
    name: "Supported forward lunge",
    shortName: "Supported lunge",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A split-stance loading pattern whose step length, depth, support, and timing must be individually cleared.",
    cues: ["Use stable support before adding challenge", "Keep the front foot planted", "Track the front knee over the mid-foot and return with control"],
    stopSignals: [...standardStopSignals, "Stop for locking, giving-way, or an uncontrolled change in knee direction."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-aspetar-aclr-cpg"],
    demoMedia: gymVisualMotion("3470-kMzUs9Y", "General forward-lunge reference without the named stable hand support"),
    media: generatedStill("supported-forward-lunge", "Supported forward-lunge exercise"),
  },
  {
    id: "band-terminal-knee-extension",
    name: "Band terminal knee extension",
    shortName: "Band knee extension",
    category: "activation",
    planEligible: false,
    equipment: ["resistance_band", "support_surface"],
    description: "A small-range standing quadriceps exercise used only with clinician-selected band tension and timing; graft choice and any associated procedure may change when it is appropriate.",
    cues: ["Anchor the band securely behind the knee", "Begin with a soft bend, then straighten without forcing", "Keep the heel down and the thigh engaged"],
    stopSignals: [...standardStopSignals, "Stop if the knee snaps backward, buckles, or develops increasing pain at the front of the knee."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-osu-aclr"],
    demoMedia: gymVisualMotion("3007-Y1MsI1l", "General resistance-band leg-extension reference; band position and movement range differ from terminal knee extension"),
    media: generatedStill("band-terminal-knee-extension", "Band terminal knee-extension exercise"),
  },
  {
    id: "chair-sit-to-stand",
    name: "Chair sit-to-stand",
    shortName: "Sit-to-stand",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A supported squat pattern from a stable chair, introduced only when current weight-bearing restrictions allow it; graft choice and associated procedures can alter timing and depth.",
    cues: ["Use a firm chair that cannot slide", "Keep both feet planted and knees aligned", "Stand and sit with smooth, even control"],
    stopSignals: [...standardStopSignals, "Stop if you drop into the chair, shift abruptly away from the affected side, or cannot rise safely."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-osu-aclr"],
    demoMedia: gymVisualMotion("3132-b63ZzGe", "General supported squat reference; the demonstration does not use a chair touch point", "generic_pattern"),
    media: generatedStill("chair-sit-to-stand", "Chair sit-to-stand exercise"),
  },
  {
    id: "supported-lateral-step-down",
    name: "Supported lateral step-down",
    shortName: "Lateral step-down",
    category: "strength",
    planEligible: false,
    equipment: ["step", "support_surface"],
    description: "A controlled single-leg lowering task from a clinician-selected step height; graft status, associated procedures, and movement criteria determine readiness.",
    cues: ["Hold stable support", "Keep the stance foot fully planted", "Lower slowly while the knee tracks over the mid-foot"],
    stopSignals: [...standardStopSignals, "Stop if the pelvis drops markedly or the stance knee collapses inward despite reducing the step height."],
    eligiblePhaseIds: ["rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-osu-aclr"],
    demoMedia: gymVisualMotion("1008-d5bTEPV", "General step-loading reference showing a banded step-up rather than a supported lateral step-down"),
    media: generatedStill("supported-lateral-step-down", "Supported lateral step-down exercise"),
  },
  {
    id: "box-assisted-single-leg-squat",
    name: "Box-assisted single-leg squat",
    shortName: "Assisted single-leg squat",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A shallow single-leg squat toward a stable box or chair with hand support; depth and timing require clinician clearance for the graft and any associated procedure.",
    cues: ["Keep stable support within reach", "Reach the hips toward the box", "Keep the knee aligned and control the return"],
    stopSignals: [...standardStopSignals, "Stop if the knee gives way, twists, or cannot stay aligned at the approved depth."],
    eligiblePhaseIds: ["rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("0411-H6ybluc", "General loaded single-leg squat reference without the named box target and hand support"),
    media: generatedStill("box-assisted-single-leg-squat", "Box-assisted single-leg squat exercise"),
  },
  {
    id: "bilateral-romanian-deadlift",
    name: "Bilateral Romanian deadlift / hip hinge",
    shortName: "Two-leg hip hinge",
    category: "strength",
    planEligible: false,
    equipment: ["none"],
    description: "A two-leg hip hinge for posterior-chain strength, performed without added load until a clinician selects it; hamstring-graft harvest and associated procedures may delay or modify loading.",
    cues: ["Keep both feet grounded", "Send the hips backward with a long spine", "Stand by driving the hips forward without momentum"],
    stopSignals: [...standardStopSignals, "Stop for pain at a hamstring graft-donor site or if knee position cannot remain controlled."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("1459-rR0LJzx", "General bilateral Romanian-deadlift reference using dumbbells rather than the unloaded hip-hinge variation"),
    media: generatedStill("bilateral-romanian-deadlift", "Bilateral Romanian deadlift exercise"),
  },
  {
    id: "heel-dig-bridge-isometric",
    name: "Heel-dig bridge / hamstring isometric",
    shortName: "Heel-dig bridge",
    category: "activation",
    planEligible: false,
    equipment: ["none"],
    description: "A bridge variation that adds isometric hamstring effort through the heels; hamstring-graft harvest and associated procedures require explicit clearance before this exercise.",
    cues: ["Set both heels comfortably on the floor", "Gently draw the heels toward you without sliding", "Lift only as high as you can keep the pelvis level"],
    stopSignals: [...standardStopSignals, "Stop for cramping, sharp posterior-thigh pain, or pain at a hamstring graft-donor site."],
    eligiblePhaseIds: ["prehab", "rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-mgh-aclr", "source-osu-aclr"],
    demoMedia: gymVisualMotion("3013-u0cNiij", "General two-leg bridge reference; it does not demonstrate the named heel-dig isometric effort", "generic_pattern"),
    media: generatedStill("heel-dig-bridge-isometric", "Heel-dig bridge isometric exercise"),
  },
  {
    id: "supported-reverse-lunge",
    name: "Supported reverse lunge",
    shortName: "Reverse lunge",
    category: "strength",
    planEligible: false,
    equipment: ["support_surface"],
    description: "A supported backward step into a split stance, with depth and load selected by the clinician; graft healing and associated procedures determine when it can begin.",
    cues: ["Hold stable support", "Step back softly and keep the front foot planted", "Keep the front knee aligned as you return"],
    stopSignals: [...standardStopSignals, "Stop for locking, giving-way, or an uncontrolled inward or outward change in knee direction."],
    eligiblePhaseIds: ["rebuild-capacity", "advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-mgh-aclr"],
    demoMedia: gymVisualMotion("0381-SSsBDwB", "General reverse-lunge reference using dumbbells and no stable hand support"),
    media: generatedStill("supported-reverse-lunge", "Supported reverse-lunge exercise"),
  },
  {
    id: "clinician-cleared-double-leg-landing",
    name: "Clinician-cleared double-leg landing drill",
    shortName: "Two-leg landing",
    category: "balance",
    planEligible: false,
    equipment: ["none"],
    description: "A low-level two-foot landing drill for supervised impact preparation only after objective clearance; graft maturation and any meniscus, cartilage, or additional ligament procedure may delay impact work.",
    cues: ["Use only the height and task selected by your clinician", "Land quietly on both feet", "Keep the hips, knees, and feet aligned as you absorb the landing"],
    stopSignals: [...standardStopSignals, "Stop immediately for pain, instability, a stiff or uneven landing, or loss of alignment."],
    eligiblePhaseIds: ["advance-performance", "return-and-maintain"],
    sourceIds: ["source-care-team", "source-aspetar-aclr-cpg", "source-mgh-aclr", "source-osu-aclr"],
    demoMedia: gymVisualMotion("3543-wfotm7S", "General two-leg drop-jump squat reference; height and landing task differ from the clinician-selected drill"),
    media: generatedStill("double-leg-landing", "Clinician-cleared double-leg landing exercise"),
  },
] as const satisfies readonly ExerciseRecord[];

/** The seven primary strengthening exercises specified for the default prehab plan. */
export const corePrehabExerciseIds = [
  "single-leg-knee-extension-machine",
  "single-leg-hamstring-curl-machine",
  "single-leg-press",
  "squat",
  "standing-single-leg-heel-raise",
  "standing-hip-abduction-external-rotation-fire-hydrant",
  "modified-single-leg-deadlift",
] as const;

const clinicianDose = {
  kind: "clinician_defined",
  note: "Use only the sets, repetitions, resistance, range, and frequency prescribed for this episode.",
} as const;

export const routines = [
  {
    id: "routine-right-prehab-foundations",
    episodeId: "episode-right-acl-2026",
    phaseId: "prehab",
    name: "Prehab foundations",
    description: "A draft movement and strength sequence to review with the treating clinician before use.",
    status: "draft",
    items: corePrehabExerciseIds.map((exerciseId, index) => ({
      id: `routine-right-prehab-${index + 1}`,
      exerciseId,
      order: index + 1,
      dose: clinicianDose,
      side: "affected" as const,
    })),
    safetyNote: SAFETY_NOTICE,
    updatedAt: "2026-08-12T09:00:00+08:00",
  },
  {
    id: "routine-left-maintenance",
    episodeId: "episode-left-knee-2024",
    phaseId: "return-and-maintain",
    name: "Maintenance reference",
    description: "A retired routine retained with its original episode rather than mixed into the active plan.",
    status: "retired",
    items: [
      { id: "routine-left-1", exerciseId: "stationary-bike", order: 1, dose: clinicianDose, side: "both" },
      { id: "routine-left-2", exerciseId: "single-leg-balance", order: 2, dose: clinicianDose, side: "alternating" },
    ],
    safetyNote: SAFETY_NOTICE,
    updatedAt: "2025-01-20T10:30:00+08:00",
  },
] as const satisfies readonly RehabRoutine[];

export const seedData = {
  generatedAt: "2026-08-12T09:00:00+08:00",
  activeEpisodeId: "episode-right-acl-2026",
  episodes: [
    {
      id: "episode-right-acl-2026",
      title: "Right knee ACL prehab",
      knee: "right",
      status: "active",
      stage: "pre_surgery",
      currentPhaseId: "prehab",
      startedOn: "2026-08-12",
      plannedSurgeryDate: "2026-12-12",
      notes: "Planned surgery is approximately four months away. Confirm the date and all restrictions with the care team.",
      updatedAt: "2026-08-12T09:00:00+08:00",
    },
    {
      id: "episode-left-knee-2024",
      title: "Left knee rehabilitation",
      knee: "left",
      status: "completed",
      stage: "post_surgery",
      currentPhaseId: "return-and-maintain",
      notes: "Previous ACL reconstruction retained separately for local history. Exact dates and procedure details have not been entered.",
      updatedAt: "2025-01-20T10:30:00+08:00",
    },
  ],
  phases: rehabPhases,
  exercises,
  routines,
  sources: sourceMetadata,
} as const satisfies KneeForwardSeedData;

export default seedData;
